# Generated by Django 5.2 on 2025-05-03 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lab_data', '0005_alter_equipmentdata_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioExperimentData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('amplitude', models.FloatField()),
                ('minima_detected', models.IntegerField(default=0)),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab_data.experiments')),
            ],
        ),
    ]
