# Generated by Django 5.2.1 on 2025-05-09 00:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('audio_processing', '0001_initial'),
        ('lab_data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='audioexperimentdata',
            name='experiment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab_data.experiments'),
        ),
    ]
