# Generated by Django 5.2.1 on 2025-05-14 00:24

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experiments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('preparing', 'Подготовка'), ('stage_1', 'Этап 1 — запись'), ('stage_2', 'Этап 2 — запись'), ('stage_3', 'Этап 3 — запись'), ('completed', 'Завершен'), ('aborted', 'Прерван')], default='started', max_length=20)),
                ('step', models.IntegerField(default=1)),
                ('temperature', models.FloatField(default=20.0, verbose_name='Температура (°C)')),
                ('tube_length', models.FloatField(default=0.5, verbose_name='Длина трубы (м)')),
                ('stages', models.JSONField(default=list, help_text="Данные этапов: [{'frequency': 1500, 'data': [...]}, {'frequency': 3000, 'data': [...]}, ...]")),
                ('student_speed', models.FloatField(null=True)),
                ('student_gamma', models.FloatField(null=True)),
                ('system_gamma', models.FloatField(null=True)),
                ('error_percent', models.FloatField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Эксперимент',
                'verbose_name_plural': 'Эксперименты',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('full_name', models.CharField(help_text='Полное имя пользователя (только кириллица)', max_length=100, verbose_name='ФИО')),
                ('email', models.EmailField(help_text='Уникальный email пользователя', max_length=254, unique=True, verbose_name='Email')),
                ('group_name', models.CharField(blank=True, help_text='Название учебной группы (кириллица + цифры)', max_length=20, null=True, verbose_name='Группа')),
                ('role', models.CharField(choices=[('student', 'Студент'), ('teacher', 'Преподаватель'), ('assistant', 'Лаборант')], default='student', help_text='Роль пользователя в системе', max_length=10, verbose_name='Роль')),
                ('is_staff', models.BooleanField(default=False, help_text='Определяет доступ к админ-панели')),
                ('is_active', models.BooleanField(default=True, help_text='Активен ли пользователь')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='date joined')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='Results',
            fields=[
                ('experiment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='lab_data.experiments')),
                ('gamma_calculated', models.FloatField(default=0.0, verbose_name='Рассчитанное γ (система)')),
                ('gamma_reference', models.FloatField(default=1.4, verbose_name='Эталонное γ')),
                ('student_gamma', models.FloatField(blank=True, null=True, verbose_name='Студенческое γ')),
                ('student_speed', models.FloatField(blank=True, null=True, verbose_name='Студенческая скорость звука (м/с)')),
                ('error_percent', models.FloatField(blank=True, help_text='Процент ошибки, может быть NULL', null=True, verbose_name='Отклонение γ студента от эталона (%)')),
                ('status', models.CharField(choices=[('success', 'Успешно'), ('fail', 'Неудача'), ('pending_student_input', 'Ожидает ввода студента'), ('completed_by_assistant', 'Завершен лаборантом'), ('final_completed', 'Полностью завершен')], default='pending_student_input', max_length=30)),
                ('visualization_data', models.JSONField(default=dict)),
                ('detailed_results', models.JSONField(default=list)),
            ],
            options={
                'verbose_name': 'Результат',
                'verbose_name_plural': 'Результаты',
            },
        ),
        migrations.AddField(
            model_name='experiments',
            name='assistant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assisted_experiments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='experiments',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='EquipmentData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_ms', models.IntegerField(verbose_name='Время (мс)')),
                ('microphone_signal', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1023)], verbose_name='Сигнал микрофона')),
                ('tube_position', models.FloatField(verbose_name='Положение трубы (мм)')),
                ('voltage', models.FloatField(verbose_name='Напряжение (В)')),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment_data', to='lab_data.experiments', verbose_name='Эксперимент')),
            ],
            options={
                'verbose_name': 'Данные оборудования',
                'verbose_name_plural': 'Данные оборудования',
                'ordering': ['time_ms'],
            },
        ),
        migrations.CreateModel(
            name='Calculations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.IntegerField(verbose_name='Номер шага')),
                ('description', models.TextField(verbose_name='Описание')),
                ('formula_used', models.TextField(blank=True, verbose_name='Использованная формула')),
                ('input_data', models.JSONField(verbose_name='Входные данные')),
                ('output_data', models.JSONField(verbose_name='Выходные данные')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Время выполнения')),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calculations', to='lab_data.experiments', verbose_name='Эксперимент')),
            ],
            options={
                'verbose_name': 'Расчёт',
                'verbose_name_plural': 'Расчёты',
                'ordering': ['step_number'],
            },
        ),
        migrations.CreateModel(
            name='Protocols',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generated_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата генерации')),
                ('protocol_path', models.CharField(max_length=255, verbose_name='Путь к протоколу')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('final', 'Финальный')], default='draft', max_length=10, verbose_name='Статус')),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='protocols', to='lab_data.experiments', verbose_name='Эксперимент')),
            ],
            options={
                'verbose_name': 'Протокол',
                'verbose_name_plural': 'Протоколы',
                'ordering': ['-generated_at'],
            },
        ),
    ]
