# Generated by Django 5.2 on 2025-04-27 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab_data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='full_name',
            field=models.CharField(default='', max_length=100, verbose_name='ФИО'),
            preserve_default=False,
        ),
    ]
