# Generated by Django 5.2 on 2025-04-27 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lab_data', '0002_users_full_name'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='users',
            managers=[
            ],
        ),
    ]
