# Generated by Django 5.2 on 2025-05-03 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab_data', '0004_results_visualization_data'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipmentdata',
            options={'ordering': ['time_ms'], 'verbose_name': 'Данные оборудования', 'verbose_name_plural': 'Данные оборудования'},
        ),
        migrations.AlterModelOptions(
            name='experiments',
            options={'ordering': ['-date'], 'verbose_name': 'Эксперимент', 'verbose_name_plural': 'Эксперименты'},
        ),
        migrations.AlterModelOptions(
            name='protocols',
            options={'ordering': ['-generated_at'], 'verbose_name': 'Протокол', 'verbose_name_plural': 'Протоколы'},
        ),
        migrations.AlterModelOptions(
            name='results',
            options={'verbose_name': 'Результат', 'verbose_name_plural': 'Результаты'},
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Определяет доступ к админ-панели'),
        ),
    ]
